debug: false
baseUrl: %PUBLIC_HOST_NAME%
databaseConfiguration:
  driver: mysql
  host: localhost
  database: flarumdb
  username: flarum
  password: passflarum
  prefix:
adminUser:
  username: admin
  password: password
  email: indiacovidforum@gmail.com
settings:
  forum_title: 'India Covid Forum'
  forum_description: 'Find help on COVID issues for India.'
